


automator:
  execution:
    runAtStartup: true
    scenarioPath: D:\dev\intellij\community\process-execution-automator\src\test\ressources\simpleusertask
    server:
      type: Camunda_7
      url: "http://localhost:8080/engine-rest"


server.port: 8088
