automator:



  scheduler:

  startup:
    scenarioPath: ./src/main/resources/loadtest
    # list of scenario separate by ;
    scenarioAtStartup: file:/C8CrawlUrlScn.json;
    # DEBUG, INFO, MONITORING, MAIN, NOTHING
    logLevel: DASHBOARD
    # string composed with DEPLOYPROCESS, WARMINGUP, CREATION, SERVICETASK, USERTASK
    # (ex: "CREATION|DEPLOYPROCESS|CREATION|SERVICETASK")
    policyExecution: DEPLOYPROCESS|WARMINGUP|CREATION|SERVICETASK|USERTASK
    filterService2: simple-task

    deepTracking: false

  logDebug: false

  # servers connection is a list of connection separate by ;
  # each connection contains a name and a type. then, other parameters depends on the type
  # <name>,CAMUNDA_7,<url>
  # <name>,CAMUNDA_8,ZeebeGatewayAddress,OperateUserName,OperateUserPassword,OperateUrl
  # <name>,CAMUNDA_8_SAAS,zeebeCloudRegister,zeebeCloudRegion,zeebeCloudClusterId,zeebeCloudClientId,clientSecret,OperateUserName,OperateUserPassword,OperateUrl

  serversConnection: Camunda7URL,CAMUNDA_7,http://localhost:8080/engine-rest; \
    Camunda8URL,CAMUNDA_8,127.0.0.1:26500,demo,demo,http://localhost:8081

  # other way to provide the list of server connection
  serversList:
    - type: "camunda7"
      name: "camunda7Local"
      url: "http://localhost:8080/engine-rest"
      workerMaxJobsActive: 20

    - type: "camunda8"
      name: "Camunda8Local"
      zeebeGatewayAddress: "127.0.0.1:26500"
      operateUserName: "demo"
      operateUserPassword: "demo"
      operateUrl: "http://localhost:8081"
      taskListUrl: "http://localhost:8082"
      workerExecutionThreads: 10
      workerMaxJobsActive: 10

    - type: "camunda8saas"
      name: "Camunda8SaaS"
      zeebeCloudRegister: "aaa"
      zeebeCloudRegion: "usa"
      zeebeClientSecret: "bbb"
      zeebeCloudClusterId: "ddd"
      zeebeCloudClientId: "eee"



  servers:
    camunda7:
      name: "Camunda7Local"
      url: "http://localhost:8080/engine-rest"
      workerMaxJobsActive: 20

    camunda8:
      name: "Camunda8Local"
      zeebeGatewayAddress: "127.0.0.1:26500"
      operateUserName: "demo"
      operateUserPassword: "demo"
      operateUrl: "http://localhost:8081"
      taskListUrl: "http://localhost:8082"
      workerExecutionThreads: 10
      workerMaxJobsActive: 10






      #zeebeCloudRegister:
      #zeebeCloudRegion:
      #clientSecret:
      #zeebeCloudClusterId:
      #zeebeCloudClientId:



server.port: 8380
scheduler.poolSize: 10