automator:



  scheduler:

  startup:
    scenarioPath: ./src/main/resources/loadtest
    # list of scenario separate by ;
    scenarioAtStartup: C7SimpleTask.json;
    # DEBUG, INFO, MONITORING, MAIN, NOTHING
    logLevel: MAIN
    # string composed with DEPLOYPROCESS, WARMINGUP, CREATION, SERVICETASK (ex: "CREATION", "DEPLOYPROCESS|CREATION|SERVICETASK")
    policyExecution: DEPLOYPROCESS|WARMINGUP|CREATION
    policyExecution2: SERVICETASK|CREATION
    # list of topice separate by ;. If empty, all services task in the scenario are started, else only the list here
    filterService3: discovery-seedextraction-retrieve;discovery-seedextraction-crawl
    filterService2: discovery-seedextraction-crawl
    filterService: simple-task

    deepTracking: false

  logdebug: false

  # servers connection is a list of connection separate by ;
  # each connection contains a name and a type. then, other parameters depends on the type
  # <name>,CAMUNDA_7,<url>
  # <name>,CAMUNDA_8,ZeebeGatewayAddress,OperateUserName,OperateUserPassword,OperateUrl
  # <name>,CAMUNDA_8_SAAS,zeebeCloudRegister,zeebeCloudRegion,zeebeCloudClusterId,zeebeCloudClientId,clientSecret,OperateUserName,OperateUserPassword,OperateUrl

  serversconnection:

  # other way to provide the list of server connection

  servers:
    camunda7:
      name: "camunda7Local"
      url: "http://localhost:8080/engine-rest"
      workerMaxJobsActive: 20

    camunda8:
      name: "Camunda8Local"
      zeebeGatewayAddress: "127.0.0.1:26500"
      operateUserName: "demo"
      operateUserPassword: "demo"
      operateUrl: "http://localhost:8081"
      taskListUrl: ""
      workerExecutionThreads: 500
      workerMaxJobsActive2: 500






      zeebeCloudRegister:
      zeebeCloudRegion:
      clientSecret:
      zeebeCloudClusterId:
      zeebeCloudClientId:



server.port: 8380
scheduler.poolSize: 10