### POST Request
POST http://localhost:8381/api/unittest/run?name=ScoreAcceptanceScn&server=Camunda8Ruby&wait=false
Content-Type: application/json

{
}


### POST Request
GET http://localhost:8381/api/unittest/get?id=1732767184446
Content-Type: application/json

{
}

### GET LIST
GET http://localhost:8381/api/unittest/list
Content-Type: application/json

{
}
