apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-creation
  labels:
    app: pa-verification-creation
spec:
  selector:
    matchLabels:
      app: pa-verification-creation
  replicas: 1
  template:
    metadata:
      labels:
        app: pa-verification-creation
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-creation
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=5
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=DEPLOYPROCESS|WARMINGUP|CREATION
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-retrieve
  labels:
    app: pa-verification-retrieve
spec:
  selector:
    matchLabels:
      app: pa-verification-retrieve
  replicas: 2
  template:
    metadata:
      labels:
        app: pa-verification-retrieve
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-retrieve
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=18
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-retrieve
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-checkurl
  labels:
    app: pa-verification-checkurl
spec:
  selector:
    matchLabels:
      app: pa-verification-checkurl
  replicas: 4
  template:
    metadata:
      labels:
        app: pa-verification-checkurl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-checkurl
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=50
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-checkurl
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-updateitem
  labels:
    app: pa-verification-updateitem
spec:
  selector:
    matchLabels:
      app: pa-verification-updateitem
  replicas: 1
  template:
    metadata:
      labels:
        app: pa-verification-updateitem
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-updateitem
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=35
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-updateitem
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-download
  labels:
    app: pa-verification-download
spec:
  selector:
    matchLabels:
      app: pa-verification-download
  replicas: 20
  template:
    metadata:
      labels:
        app: pa-verification-download
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-download
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=50
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-download
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-fingerprint
  labels:
    app: pa-verification-fingerprint
spec:
  selector:
    matchLabels:
      app: pa-verification-fingerprint
  replicas: 28
  template:
    metadata:
      labels:
        app: pa-verification-fingerprint
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-fingerprint
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=75
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-fingerprint
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-getresult
  labels:
    app: pa-verification-getresult
spec:
  selector:
    matchLabels:
      app: pa-verification-getresult
  replicas: 56
  template:
    metadata:
      labels:
        app: pa-verification-getresult
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-getresult
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=38
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-getresult
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-obtaindescription
  labels:
    app: pa-verification-obtaindescription
spec:
  selector:
    matchLabels:
      app: pa-verification-obtaindescription
  replicas: 2
  template:
    metadata:
      labels:
        app: pa-verification-obtaindescription
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-obtaindescription
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=52
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-obtaindescription
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-thresoldcheck
  labels:
    app: pa-verification-thresoldcheck
spec:
  selector:
    matchLabels:
      app: pa-verification-thresoldcheck
  replicas: 1
  template:
    metadata:
      labels:
        app: pa-verification-thresoldcheck
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-thresoldcheck
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=34
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-thresoldcheck
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-verification-createpotentialclaim
  labels:
    app: pa-verification-createpotentialclaim
spec:
  selector:
    matchLabels:
      app: pa-verification-createpotentialclaim
  replicas: 1
  template:
    metadata:
      labels:
        app: pa-verification-createpotentialclaim
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: pa-verification-createpotentialclaim
          image: pierreyvesmonnet/processautomator:1.0.3
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dautomator.servers.camunda8.zeebeGatewayAddress=camunda-zeebe-gateway:26500
                -Dautomator.servers.camunda8.operateUserName=demo
                -Dautomator.servers.camunda8.operateUserPassword=demo
                -Dautomator.servers.camunda8.operateUrl=http://camunda-operate:80
                -Dautomator.servers.camunda8.taskListUrl=
                -Dautomator.servers.camunda8.workerExecutionThreads=34
                -Dautomator.servers.camunda8.workerMaxJobsActive=15
                -Dautomator.startup.scenarioPath=/app/scenarii/loadtest
                -Dautomator.startup.scenarioAtStartup=Verification.json
                -Dautomator.startup.waitWarmup=PT10S
                -Dautomator.startup.policyExecution=SERVICETASK|USERTASK
                -Dautomator.startup.filterService=verification-createpotentialclaim
                -Dautomator.startup.logLevel=MAIN
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
